# Generated by Django 2.2 on 2019-03-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalTrackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=200)),
                ('Calories', models.CharField(default='', max_length=200)),
                ('Date', models.DateField(default='')),
            ],
        ),
    ]
